<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Assembly Info">
    <RootNamespace>InitializeBinFolder.Standalone</RootNamespace>
    <StartupObject>InitializeBinFolder.Program</StartupObject>
  </PropertyGroup>

  <PropertyGroup Label="Build">
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.49.1" />
    <PackageReference Include="Spectre.Console.Extensions.Logging" Version="0.2.1" />
    <PackageReference Include="Spectre.Console.Extensions.Table" Version="1.0.0" />
    <PackageReference Include="Spectre.Console.Extensions.Progress" Version="1.0.0" />
  </ItemGroup>

</Project>
